- name: Restaurar servidor de recuperación
  hosts: recovery
  become: true
  tasks:
    - name: Instalar Apache
      package:
        name: "{{ apache }}"
        state: present

    - name: Restaurar configuración de Apache
      copy:
        src: ../files/backup/reports/tmp/web-backup/httpd.conf
        dest: /etc/httpd/conf/httpd.conf

    - name: Restaurar contenido web
      unarchive:
        src: ../files/backup/reports/tmp/web-backup/html.tar.gz
        dest: /var/www/
        remote_src: no

    - name: Iniciar Apache
      service:
        name: httpd
        state: started

    - name: Validar disponibilidad del sitio restaurado
      uri:
        url: http://{{ inventory_hostname }}
        return_content: yes
